stages:
  - build
  - deploy

build_staging:
  stage: build
  cache:
    paths:
      - node_modules/
      - gems/
  script:
    - node -v
    - npm -v
    - bundle install --path gems/
    - npm install
    - gulp build:staging
  artifacts:
    paths:
      - staging
  only:
    - master

#deploy_staging:
#  stage: deploy
#  script:
#    - rsync -az --delete --progress staging/ nils@strandrover.com:/var/www/andersch.strandrover.com
#  only:
#    - master
